sudo: false
language: c

addons: {apt: {sources: [hvr-ghc]}}

cache:
  apt: true
  directories:
      - $HOME/.stack

matrix:
    include:
        - env: GHCVER=7.8.4 RESOLVER=lts-2
          addons: {apt: {packages: [ghc-7.8.4], sources: [hvr-ghc]}}
        - env: GHCVER=7.10.2 RESOLVER=lts-3
          addons: {apt: {packages: [ghc-7.10.2], sources: [hvr-ghc]}}


before_install:
    - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH
    - mkdir -p ~/.local/bin
    - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    - ghc --version
    - stack --version

install:
    - ./scripts/travis_long stack --resolver $RESOLVER --no-terminal --skip-ghc-check setup
    - ./scripts/travis_long stack --resolver $RESOLVER --no-terminal --skip-ghc-check test --only-snapshot

script:
    - stack --resolver $RESOLVER --no-terminal --skip-ghc-check test
